backend:
  name: github
  repo: joodeci/portfolio-21

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: thumbnail, label: "Thumbnail", widget: "image", required: false }
      - { label: "Description", name: "description", widget: "text", required:false }
      - { name: path, label: Path }
      - { name: body, label: Body, widget: markdown }
